baseURL = 'https://raxen001.github.io/'
languageCode = 'en-us'
title = 'Raxen abode'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark256'
    tabWidth = 4


[author]
  name = "Raxen"
  # headline = "An awesome person"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
     { linkedin = "https://linkedin.com/in/rithesh-s-05617b22a" },
     { github = "https://github.com/Raxen001" },
     { email = "mailto:rithesh.satheesh@gmail.com" },
     { link = "https://raxen001.github.io" },
     # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
     # { apple = "https://www.apple.com" },
     # { codepen = "https://codepen.io/username" },
     # { dev = "https://dev.to/username" },
     { discord = "https://discord.gg/users/401418972248932352" },
     # { dribbble = "https://dribbble.com/username" },
     # { facebook = "https://facebook.com/username" },
     # { flickr = "https://www.flickr.com/photos/username/" },
     # { foursquare = "https://foursquare.com/username" },
     # { gitlab = "https://gitlab.com/username" },
     # { google = "https://www.google.com/" },
     { instagram = "https://instagram.com/raxen001" },
     # { keybase = "https://keybase.io/username" },
     # { kickstarter = "https://www.kickstarter.com/profile/username" },
     # { lastfm = "https://lastfm.com/user/username" },
     # { mastodon = "https://mastodon.instance/@username" },
     # { medium = "https://medium.com/username" },
     # { microsoft = "https://www.microsoft.com/" },
     # { patreon = "https://www.patreon.com/username" },
     { pinterest = "https://pinterest.com/RaxenGamer001" },
     { reddit = "https://reddit.com/user/raxengamer001" },
     # { slack = "https://workspace.url/team/userid" },
     { snapchat = "https://snapchat.com/add/raxen001" },
     # { soundcloud = "https://soundcloud.com/username" },
     # { stack-exchange = "https://stackexchange.com/users/userid/username" },
     # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
     { steam = "https://steamcommunity.com/profiles/76561199059739788/" },
     # { telegram = "https://t.me/username" },
     # { tiktok = "https://tiktok.com/@username" },
     # { tumblr = "https://username.tumblr.com" },
     # { twitch = "https://twitch.tv/username" },
     # { twitter = "https://twitter.com/username" },
     # { whatsapp = "https://wa.me/phone-number" },
     { youtube = "https://youtube.com/@raxengamer001" },
  ]
