#IP="$(hostname -I | awk '{print $1}')"
IP="0.0.0.0"
# IP="legion.tailaadcc.ts.net"
LOCAL_IP="127.0.0.1"
xdg-open "http://$IP:1313"
hugo serve -D --navigateToChanged --bind "$IP" --baseURL "http://$IP/"
